# Site settings
title: 倒闭的皮革厂
SEOTitle: 倒闭的皮革厂 | ZJ Blog
header-img: img/post-bg-desk.jpg
email: giantdwarf1995@gmail.com
description: "Stay foolish. Stay hungry."
keyword: "ZJ, ZJ Blog, 倒闭的皮革厂, ZJ的博客, React, JavaScript, Flutter"
url: "https://giantdrawf.github.io/" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/GiantDrawf/GiantDrawf.github.io" # you code repository

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "奥利给!"
sidebar-avatar: /img/about-ZJ-gentle.jpeg # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
# weibo_username:     qiubaiying
# zhihu_username: qiubaiying
# github_username: qiubaiying
# facebook_username: baiying.qiu.7
# jianshu_username: e71990ada2fd
#twitter_username:   qiubaiying

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM # use Github Flavored Markdown !important

# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: giantdrawf

# Gitalk
gitalk:
  enable: false #是否开启Gitalk评论
  clientID: 6b62de6b3d5f5dad7f3f #生成的clientID
  clientSecret: 94e97c8da3f1b4d6cbd60da427f52dba7940f67e #生成的clientSecret
  repo: GiantDrawf.github.io #仓库名称
  owner: GiantDrawf #github用户名
  admin: GiantDrawf
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: cc1ea0ce15a99b6b20c77fada9bf2faf

# Google Analytics
ga_track_id: "UA-170962953-1" # Format: UA-xxxxxx-xx
ga_domain: auto # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Featured Tags
featured-tags: true # 是否使用首页标签
featured-condition-size: 0 # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true
# Friends
# friends: []
